services:
  - type: web
    name: auto-reply-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    startCommand: python main.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: GEMINI_KEYS
        sync: false
      - key: YOUTUBE_API_KEYS
        sync: false
      - key: REPLY_DELAY_MIN
        value: "1"
      - key: REPLY_DELAY_MAX
        value: "4"
      - key: OWNER_ID
        sync: false
      - key: AI_SYSTEM_PROMPT
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: autoreply-db
          property: connectionString

databases:
  - name: autoreply-db
    plan: free
    databaseName: autoreply_db
    user: autoreply_user
